# Properties
spring:
  rsocket:
    server:
      port: 7777

      transport: websocket
      mapping-path: /

logging:
  level:
      org:
        springframework:
          security:
            rsocket: DEBUG
      io:
        rsocket: DEBUG