# Properties
spring:
  rsocket:
    server:
      port: 7777
      transport: websocket
      mapping-path: /rsocket
#    message-mapping:
#      mime-type: application/json
#    metadata-mapping:
#      mime-type: message/x.rsocket.composite-metadata.v0

logging:
  level:
      org:
        springframework:
          security:
            rsocket: DEBUG
      io:
        rsocket: DEBUG